AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false
